export const CREATE_BLOG_REQUEST="CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS="CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL="CREATE_BLOG_FAIL";

export const GET_BLOG_REQUEST="GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS="GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL="GET_BLOG_FAIL";

export const GET_SINGLE_BLOG_REQUEST="GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS="GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAIL="GET_SINGLE_BLOG_FAIL";

export const UPDATE_SINGLE_BLOG_REQUEST="UPDATE_SINGLE_BLOG_REQUEST";
export const UPDATE_SINGLE_BLOG_SUCCESS="UPDATE_SINGLE_BLOG_SUCCESS";
export const UPDATE_SINGLE_BLOG_FAIL="UPDATE_SINGLE_BLOG_FAIL";

export const DELETE_SINGLE_BLOG_REQUEST="DELETE_SINGLE_BLOG_REQUEST";
export const DELETE_SINGLE_BLOG_SUCCESS="DELETE_SINGLE_BLOG_SUCCESS";
export const DELETE_SINGLE_BLOG_FAIL="DELETE_SINGLE_BLOG_FAIL";


export const GET_ALL_BLOG_REQUEST="GET_ALL_BLOG_REQUEST";
export const GET_ALL_BLOG_SUCCESS="GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_FAIL="GET_ALL_BLOG_FAIL";

export const RESET_CLEAR="RESET_CLEAR";