export const SIGNUP_REQUEST="SIGNUP_REQUEST"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAIL="SIGNUP_FAIL"

export const VERIFY_REQUEST="VERIFY_REQUEST"
export const VERIFY_SUCCESS="VERIFY_SUCCESS"
export const VERIFY_FAIL="VERIFY_FAIL"

export const RESEND_OTP_REQUEST="RESEND_OTP_REQUEST"
export const RESEND_OTP_SUCCESS="RESEND_OTP_SUCCESS"
export const RESEND_OTP_FAIL="RESEND_OTP_FAIL"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const LOGIN_VALID="LOGIN_VALID"

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 
export const LOGOUT_FAIL = 'LOGOUT_FAIL'; 

export const FORGET_PASSWORD_REQUEST="FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_SUCCESS="FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_FAIL="FORGET_PASSWORD_FAIL"

export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"

export const PROFILE_REQUEST="PROFILE_REQUEST"
export const PROFILE_SUCCESS="PROFILE_SUCCESS"
export const PROFILE_FAIL="PROFILE_FAIL"


export const RESET_CLEAR = 'RESET_CLEAR'
